[package]
name = "chat"
version = "0.1.0"
authors = ["Ralph Parkison <chesslunatic@gmail.com>"]

[dependencies]
diesel = { version = "1.0.0-rc1", features = ["postgres"] }
dotenv = "0.9.0"
iron = "0.6.0"
router = "*"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0"
time = "0.1.38"